### ISSUE TITLE
Googlebar Dark not being applied to main www.google.com?

### ISSUE THREAD

**Issue by CollinChaffin** [Devo7v/UserCSS#5]
Was this by design that the only google site it doesn't operate on is the primary Google search at www.google.com?

**Comment by Devo7v** [comment]
That is correct.  The Google search page doesn't use the same type of bar as the other Google sites.  The Google search page really requires it own style in order to properly theme it and is outside the scope of this style.

I've tried a lot of different styles to theme the Google search page, but because Google is constantly making updates, the styles must be continually updated as well and over time they just aren't.  I suggest using the [Dark Reader](https://darkreader.org/) extension, which I've found to be the most consistent.
